export const CartTypes = {
  ADD_TO_CART_REQUEST: '@cart/ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: '@cart/ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: '@cart/ADD_TO_CART_FAILURE',
  REMOVE_FROM_CART: '@cart/REMOVE_FROM_CART',
  UPDATE_AMOUNT_REQUEST: '@cart/UPDATE_AMOUNT_REQUEST',
  UPDATE_AMOUNT_SUCCESS: '@cart/UPDATE_AMOUNT_SUCCESS',
  UPDATE_AMOUNT_FAILURE: '@cart/UPDATE_AMOUNT_FAILURE',
  GET_CHECKOUT: '@cart/GET_CHECKOUT'
}
