site_name: test-front
edit_uri: https://github.com/belezanaweb/test-front/edit/main/docs/

plugins:
  - techdocs-core
  - kroki:
      ServerURL: "https://alquimia-api.gb.tech/api/proxy/kroki"
      FencePrefix: ""

nav:
  - Home: README.md
