version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
orbs:
  codecov: codecov/codecov@1.0.2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn
      - run: yarn build
  test:
    executor: node
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - codecov/upload:
          file: coverage/coverage.json
