export const CART_PRODUCTS_SUCCESS = 'CART_PRODUTCS_SUCCESS'
export const CART_PRODUCTS_ERROR = 'CART_PRODUTCS_ERROR'

export const CART_PAYMENT_SUCCESS = 'CART_PAYMENT_SUCCESS'
export const CART_PAYMENT_ERROR = 'CART_PAYMENT_ERROR'