export default {
  mainColor: "#FF7800",
  mainBackgroundColor: "#EEE",
  containerBackground: "#FFF",
  btnBackgroundColor: "#FF6C00",
  btnTextColor: "#FFF",
  btnShadowColor: "#D45A00",
  inputDefaultBorderColor: "#E7E7E7",
  inputDefaultPlaceholderColor: "#E0E7EE",
  inputDefaultValueColor: "#212121",
  inputFocusBorderColor: "#A43287",
  inputErrorDefaultColor: "#F30",
  textTitleColor: "#212122",
  textColor: "#777",
};
