export const colors = {
  buttonHover: "#D45A00",
  buttonDefault: "#FF6C00",
  textButton: "#FFF",
  inputLabelColor: "#CCC",
  inputFocusColor: "#A43287",
  inputBorderColor: "#E7E7E7",
  inputPlaceholder: "#E0E7EE",
  borderColorLight: "#EEE",
  borderColorDark: "#CCC",
  highLightColor: "#FF7800",
  backgroundColorLight: "#FFF",
  titleColor: "#999",
  errorColor: "#F30",
};
